config/routes.rb
Workoutwars::Application.routes.draw do
  root :to => "static#index"

  get '/user_exercises/users/:id', to: 'users#user_exercises'

  resources :challenge_attempts
  resources :exercise_types
  resources :competition_types
  resources :challenge_types
  
  resources :challenges do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end
  resources :exercises, only: [:new, :create, :destroy]
  resources :competitions do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end

  resources :competable_registrations, only: [:create, :destroy]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:index, :show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      devise_for :users
    end
  end 
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :difficulty
  belongs_to :competition_type
  belongs_to :category

  # Polymorphic Associations
  has_many :competable_transactions, as: :transactable, dependent: :destroy
  has_many :competable_registrations, as: :registerable, dependent: :destroy
  has_many :competable_exercises, as: :competable, dependent: :destroy
  has_many :teams, as: :teamable, dependent: :destroy
  has_many :experience_sources, as: :experienceable

  # Associations
  has_many :users, through: :competable_registrations, source: :user
  has_many :exercise_types, through: :competable_exercises
  
  accepts_nested_attributes_for :competable_exercises, allow_destroy: true
  accepts_nested_attributes_for :teams, allow_destroy: true

  validates_presence_of :name
  validates_presence_of :public
  validates_uniqueness_of :name, case_sensitive: false

  after_create :create_teams, :unless => Proc.new{ self.team == false }

  def creator
    User.find_by(id: creator_id)
  end

  def winner
    team? ? Team.find_by(id: winner_id) : User.find_by(id: winner_id)
  end

  def visibility
    public? ? "Public" : "Private"
  end

  def registered?(user)
    competable_registrations.find_by(user: user).present?
  end

  def user_registration(user)
    competable_registrations.find_by(user: user)
  end

  def team_registration(team)
    competable_registrations.find_by(team: team)
  end

  def users_by_rank
    users.sort { |a, b| a.total_xp_for_competition(self) <=> b.total_xp_for_competition(self) }.reverse
  end

  def contains_exercise_type?(exercise_type)
    competable_exercises.where(exercise_type: exercise_type).present?
  end

  def level
    difficulty.level if difficulty
  end
  
  def type
    self.team? ? 'Team' : 'Individual'
  end

  def set_win_condition(user)
    return if self.name == "Global"
    return if self.competition_type.use_limit == false
    self.team? ? set_team_win_condition : set_individual_win_condition(user)
  end

  def set_individual_win_condition(user)
    result = []
    competable_exercises.each do |comp_e|       
      comp_e.metrics.each do |metric|      
        exercise_total = user_total_by_exercise_type_and_metric(user, comp_e.exercise_type, metric)
        result << (exercise_total >= comp_e.limit)
      end  
    end
     
    is_won = result.all? { |r| r } # returns true if all limits met
    set_winner(user) if is_won
  end

  def set_team_win_condition
    result = []
    competable_exercises.each do |comp_e|       
      comp_e.metrics.each do |metric| 
        teams.each do |team|         
          team_metric_total = 0
          team.users.each do |user|
            team_metric_total += user_total_by_exercise_type_and_metric(user, comp_e.exercise_type, metric)
          end
          result << (team_metric_total >= comp_e.limit) 
        end  
      end  
    end
    is_won = result.any? { |r| r } # will contain a true if any team met the limit
    
    if is_won
      teams.each_with_index do |team, index|
        if result[index] 
          set_winner(team)
          return
        end
      end
    end
    
  end

  def user_total_by_exercise_type_and_metric(user, exercise_type, metric)
    exercises = user.exercises_for_competition_by_exercise_type(self, exercise_type)
    exercises.sum { |exercise| exercise.send(metric) }
  end

  # set_winner_for_total_xp(:team) for teams
  # set_winner_for_total_xp(:user) for individual
  def set_winner_for_total_xp(user_or_team)
    return if Date.today < end_date     
    units = competable_registrations.collect{|comp_s| comp_s.send(user_or_team)}
    winner = units.max { |a, b| a.total_xp_for_competition(self) <=> b.total_xp_for_competition(self) }     
    set_winner(winner)
  end

  def set_winner(user_or_team)
    subscription = user_registration(user_or_team) if user_or_team.kind_of? User
    subscription = team_registration(user_or_team) if user_or_team.kind_of? Team
    subscription.rank = 1
    subscription.save
    self.active = false
    self.winner_id = user_or_team.id
    self.save
  end

  def self.compute_winners_for_date_based_competitions
    comp_type = CompetitionType.find_by(name: 'Most XP by Date')
    comps = Competition.where(active: true, competition_type_id: comp_type.id)
    comps.each do |comp|
      comp.team? ? comp.set_winner_for_total_xp(:team) : comp.set_winner_for_total_xp(:user)
    end
  end

  def create_teams
    count = self.number_of_teams - self.teams.count
    count.times do 
      self.teams.create!
    end
  end
end

app/models/competition_type.rb
class CompetitionType < ActiveRecord::Base
  has_many :competitons

  def self.default_scope
    order('name ASC')
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  def index
    @competitions = Competition.all
  end

  def show
    @registration = @competition.competable_registrations.find_by(user_id: current_user.id)
    @registration = CompetableRegistration.new if @registration.nil? 
  end

  def new
    @competition = Competition.new
  end

  def edit
  end

  def create
    @competition = Competition.new(competition_params)
    @competition.creator_id = current_user.id

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @competition }
      else
        format.html { render action: 'new' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_path, notice: 'Competition was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_competition
      @competition = Competition.find(params[:id])
    end

    def competition_params
      params.require(:competition).permit(
        :name, :start_date, :end_date, :max_participants, :lower_level_restriction, :upper_level_restriction,
        :difficulty_id, :public, :number_of_teams, :competition_type_id, :team,
        :competable_exercises_attributes => [:id, :competable_id, :competable_type, :exercise_type_id, :limit, :_destroy]
      )
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competable_exercise_fields.html.haml
%fieldset
  %table.table.table-condensed
    %tr
      %td
        = f.hidden_field :competition_id, value: @competition.id
        = f.label :exercise_type_id, class: "control-label"
      %td
        = f.collection_select(:exercise_type_id, ExerciseType.all, :id, :name, {}, {:class => 'exercise-select'})
      %td
        = f.label :limit, class: "control-label use_limit"
      %td
        = f.number_field :limit, class: "use_limit"
      %td
        = f.hidden_field :_destroy
        = link_to "remove", '#', class: "btn btn-danger remove_fields"

app/views/competitions/_competition.html.haml
#accordion.panel-group
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %a.accordion-toggle{"data-parent" => "#accordion", "data-toggle" => "collapse", href: "#collapse#{competition.id}"}
          = competition.name
          = link_to "Withdraw", competable_registration_path(competition.user_registration(current_user)), method: :delete, class: "btn btn-xs btn-default pull-right"
    .panel-collapse.collapse{id: "collapse#{competition.id}"}
      .panel-body
        %ul         
          %li
            %table{class: "table table-hover", style: "width: 600px;"}
              -competition.competable_exercises.each do |comp_exercise|
                %tr
                  %th
                    = comp_exercise.exercise_type.name
                    - comp_exercise.metrics.each do |metric|              
                      %th
                        = metric 
                  %th
                    XP
                %tr
                  %td
                  - comp_exercise.metrics.each do |metric|
                    %td
                      = current_user.competition_total_for(competition, comp_exercise.exercise_type, metric)
                  %td
                    = current_user.competition_total_for(competition, comp_exercise.exercise_type, :total_xp)

app/views/competitions/_competition_exercise_fields.html.haml
%fieldset
  %table.table.table-condensed
    %tr
      %td
        = f.hidden_field :competition_id, value: @competition.id
        = f.label :exercise_type_id, class: "control-label"
      %td
        = f.collection_select(:exercise_type_id, ExerciseType.all, :id, :name, {}, {:class => 'exercise-select'})
      %td
        = f.label :limit, class: "control-label"
      %td
        = f.number_field :limit
      %td
        = f.hidden_field :_destroy
        = link_to "remove", '#', class: "btn btn-danger remove_fields"

app/views/competitions/_form.html.haml
= form_for @competition do |f|
  .row.competition-form
    .col-md-4
      %h1 New competition
      %hr
      - if @competition.errors.any?
        #error_explanation
          %h2= "#{pluralize(@competition.errors.count, "error")} prohibited this competition from being saved:"
          %ul
            - @competition.errors.full_messages.each do |msg|
              %li= msg
      .control-group
        .controls
          = label :team, "Team"
          = f.radio_button :team, true
          = label :team, "Individual"
          = f.radio_button :team, false

      .control-group
        = f.label :name, "Competition Name", class: "control-label"
        .controls
          = f.text_field :name

      .control-group.team_show
        = f.label :number_of_teams, "Number of Teams", class: "control-label"
        .controls
          = f.number_field :number_of_teams

      .control-group
        = f.label :competition_type_id, "Victory Condition", class: "control-label"
        .controls
          = f.collection_select(:competition_type_id, CompetitionType.all, :id, :name)

      .control-group
        = f.label :difficulty_id, "Difficulty Rating", class: "control-label"
        .controls
          = f.collection_select(:difficulty_id, Difficulty.all, :id, :level)

      .control-group
        = f.label :end_date, class: "control-label"
        .controls
          = f.text_field :end_date, class: "datepicker"

      .control-group
        = f.label :max_participants, class: "control-label"
        .controls
          = f.number_field :max_participants

      .control-group
        .controls
          = label :public, "Public"
          = f.radio_button :public, true
          = label :public, "Private"
          = f.radio_button :public, false
    
    .col-md-8  
      %h1 Exercises for this competition
      %hr
      -if @competition.competable_exercises.empty?
        - @competition.competable_exercises.build

      = link_to_add_fields "Add Another Exercise", f, :competable_exercises
      = f.fields_for :competable_exercises do |builder|
        = render 'competable_exercise_fields', f: builder
          
          
      .actions
        = f.submit 'Save Competition', class: 'btn btn-lg btn-primary', rel: 'save-competition-link'

app/views/competitions/edit.html.haml
%h1 Editing competition

= render 'form'

app/views/competitions/index.html.haml
%h1 Listing competitions
= link_to 'New Competition', new_competition_path, class: "btn btn-lg btn-primary", rel: 'new-competition-link'
%hr
.row
  .col-md-10
    %table.table.table-condensed.table-bordered
      %tr
        %th Name
        %th Win Condition
        %th Start date
        %th End date
        %th Registered Participants
        %th Max participants
        %th Difficulty
        %th Private

      - @competitions.each do |competition|
        %tr
          %td= link_to competition.name, competition
          %td= competition.competition_type.name
          %td= competition.start_date
          %td= competition.end_date
          %td= competition.users.count
          %td= competition.max_participants
          %td= competition.level
          %td= competition.visibility
    %br

  .col-md-2
    

app/views/competitions/new.html.haml
= render 'form'

app/views/competitions/show.html.haml
.row
  .col-md-3
    %h1 
      = @competition.name
  .col-md-6
    %h1
      Competition Type:
      = @competition.type
%hr/
- if @competition.team?
  -@competition.teams.each do |team|
    %p
      Team
      = team.id
    %p
      -if @competition.registered?(current_user)
        -if @registration.team == team
          = link_to "Leave This Team", @registration, method: :delete, class: "btn btn-lg btn-primary"
      -else
        = form_for @registration do |f|
          = f.hidden_field :registerable_id, value: @competition.id
          = f.hidden_field :registerable_type, value: "Competition"
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :team_id, value: team.id
          .actions
            = f.submit "Join This Team", class: "btn btn-lg btn-primary"
    %ul
      - team.users.each do |user|
        %li
          = user.index_name

-else
  - if @competition.registered?(current_user)
    = link_to "Admit Defeat", @registration, method: :delete, class: "btn btn-lg btn-primary"
  -else
    = form_for @registration do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :registerable_id, value: @competition.id
      = f.hidden_field :registerable_type, value: "Competition"
      .actions
        = f.submit "Register", class: "btn btn-lg btn-primary"
.row
  .col-md-4 
    %h3
      Competition Status:
      - if @competition.active?
        active 
      - else
        inactive
    %p
      %span
        %b Start Date:   
        = show_date(@competition.start_date)
    %p
      %span
        %b End Date:
        = show_date(@competition.end_date)
    %p
      %span
        %b Max Participants:
        = @competition.max_participants
    %p
      %span
        %b Difficulty:
        = @competition.level
    %p
      %span
        %b Visibility:   
        -if  @competition.public?
          Public
        -else
          Private 
  .col-md-4 
    %h3 Exercises for this Competition
    %p
      .row
        .col-md-3 
          %ul
            - @competition.competable_exercises.each do |exercise|
              %li
                = exercise.exercise_type.name
                =# exercise.limit
                =# link_to "Remove from Competition", competition_competable_exercise_path(@competition, exercise), method: :delete, confirm: "You Sure?", rel: 'delete-competiton-exercise-link'   
      
%hr/
%h3 Rank
.row
  .col-md-8
    %ul
      - @competition.users_by_rank.each_with_index do |user, index|
        %li      
          = index+1 
          = user.name
          = user.total_xp_for_competition(@competition)
    