config/routes.rb
Workoutwars::Application.routes.draw do
  root :to => "static#index"

  get '/user_exercises/users/:id', to: 'users#user_exercises'

  resources :challenge_attempts
  resources :exercise_types
  resources :competition_types
  resources :challenge_types
  
  resources :challenges do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end
  resources :exercises, only: [:new, :create, :destroy]
  resources :competitions do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end

  resources :competable_registrations, only: [:create, :destroy]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:index, :show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      devise_for :users
    end
  end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :token_authenticatable,
         :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  validates :email, presence: true
  validates_presence_of :password_confirmation, on: :create
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 6 }, unless: Proc.new { |u| u.password.blank? }

  before_create :generate_nickname

  has_many :experience_sources
  has_many :exercises
  has_many :challenge_attempts
  has_many :challenges, through: :challenge_attempts
  has_many :competable_registrations
  has_many :competitions, through: :competable_registrations, source: :registerable, source_type: 'Competition'
  has_many :teams, through: :competable_registrations, source: :team
  has_many :competable_transactions, dependent: :destroy  
  has_many :friendships, foreign_key: "user_id", dependent: :destroy
  has_many :occurances_as_friend, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user.nil?
      user = User.create(name:auth.extra.raw_info.name, provider:auth.provider, 
                         uid:auth.uid, email:auth.info.email, password:Devise.friendly_token[0,20])
    end
    user
  end

  def index_name
    secondary = name ? name : email
    "#{self.nickname} (#{secondary})"
  end

  def friends
    occurances_as_friend.collect(&:user) + friendships.collect(&:friend)
  end

  def challenge_attempts_by_challenge(challenge)
    challenge_attempts.where(challenge: challenge)
  end

  def competitions_won
    competable_registrations.where(rank: 1).collect{|comp_s| comp_s.registerable}.flatten   
  end

  def active_competitions
    competitions.where(active: true)
  end
  
  def active_team_competitions
    active_competitions.collect{|c| c if c.teams.count > 0}.reject(&:nil?)
  end

  def active_individual_competitions
    competitions.where(active: true, team: false)
  end

  def exercises_by_exercise_type_id(id)
    exercises.where(exercise_type_id: id)
  end

  def exercises_by_date(date)
    exercises.where("date(created_at) = (?)", date)
  end

  def competable_transactions_for_competition(competition)
    return [] if competition.nil?
    self.competable_transactions.where(transactable: competition)
  end

  def exercises_for_competition(competition)
    return [] if competition.nil?
    competable_transactions_for_competition(competition).collect {|comp_t| comp_t.exercise}.compact
  end

  def exercises_for_competition_by_exercise_type(competition, exercise_type)
    competable_transactions_for_competition(competition).collect{|comp_t| comp_t.exercise if comp_t.exercise.exercise_type_id == exercise_type.id}.compact
  end

  def xp
    self.experience_sources.sum(:amount)
  end

  def next_level_xp
    self.xp_level * self.xp_multiplier
  end

  def previous_level_xp
    (self.xp_level-1) * (self.xp_multiplier-100)
  end

  def xp_for_levelup
    next_level_xp - xp
  end

  def set_level
    while xp >= next_level_xp
      self.level += 1
      self.xp_level += 1
      self.xp_multiplier += 100
    end 
    while xp < previous_level_xp
      break if self.xp_level == 1
      self.level -= 1
      self.xp_level -= 1
      self.xp_multiplier -= 100
    end 
    self.save
  end

  def competition_total_for(competition, exercise_type, category)
    total = 0
    comp_transactions = competable_transactions.where(transactable: competition)
    comp_transactions.each do |transaction|
      if transaction.exercise.exercise_type == exercise_type
        total += transaction.exercise.send(category)
      end
    end
    total
  end

  def total_xp_for_competition(competition)
    comp_transactions = competable_transactions.where(transactable: competition)
    result = 0
    comp_transactions.each do |comp_t|
      result += comp_t.exercise.total_xp
    end
  end

  def create_competable_transactions(exercise)
    comps_for_exercise = active_competitions.collect{|c| c if c.contains_exercise_type?(exercise.exercise_type)}.compact
    comps_for_exercise.each do |comp|
      competable_transactions.create(exercise: exercise, transactable: comp)
    end
  end

  def generate_nickname
    self.nickname = Nickname.get_nickname
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sesssions_controller.rb
class Users::SessionsController < Devise::SessionsController
  append_view_path 'app/views/devise'
    def create
      respond_to do |format|
        format.html { super }
        format.json {
          warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
          current_user.ensure_authentication_token!
          render :json => {:user => current_user.api_attributes, :auth_token => current_user.authentication_token}.to_json, :status => :ok
        }
      end
    end

    def destroy
      respond_to do |format|
        format.html { super }
        format.json {
          warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
          current_user.empty_authentication_token!
          render :json => {}.to_json, :status => :ok
        }
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    @exercises = @user.exercises
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to user_path(@user), notice: 'Something went wrong' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def user_exercises
    @user = User.find(params[:id])
    respond_to do |format|
      format.json { render json: @user.exercises_by_exercise_type_id(params[:exercise_type_id]) }
    end
  end

private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, 
      :address, :phone, :weight, :height, :gender
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def exercise_date_range(date)
    "#{format_date(start_date(date))} - #{format_date(date)}"
  end

  def exercise_date_days(date)
    initial = start_date(date)
    days = []
    7.times do 
      days << initial
      initial += 1.day
    end
    days
  end

  def start_date(date)
    date - 6.days
  end

  def format_date(date)
    date.strftime("%m-%d-%Y")
  end
end

app/views/users/_edit.html.haml
%h2
  Editing #{@user.nickname}

= form_for @user do |f|
  .control-group
    = f.label "What your Mom calls you", class: "control-label"
    .controls
    = f.text_field :name, placeholder: "Name"

  .control-group
    = f.label "What your friends would call you, if they were smart", class: "control-label"
    .controls
    = f.text_field :nickname, placeholder: "Nickname"

  .control-group
    .controls
      = f.radio_button :gender, "Male", :checked => true 
      = label :gender, "Male"
      = f.radio_button :gender, "Female"
      = label :gender, "Female"
      = f.radio_button :gender, "Other"
      = label :gender, "Other"      

  .control-group
    = f.label "Your body's relative mass", class: "control-label"
    .controls
      = f.number_field :weight, placeholder: "Weight"
      %br
      %i (This will not be publicly shared, unless you want to!)

  .control-group
    = f.label "Age", class: "control-label"
    .controls
      = f.number_field :age, placeholder: "Age"

  .control-group
    = f.label :height, class: "control-label"
    .controls
      = f.number_field :height, placeholder: "Height"

  .actions
    = f.submit "Update", class: "btn btn-primary"
%p
  = link_to "Click here to change your email, password", edit_user_registration_path
%h3 Cancel my account
%p
  Unhappy? #{button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete}
= link_to "Back", :back

app/views/users/_menu.html.haml
%ul{id: "tabMenu", class: "nav nav-tabs"}
  %li.active
    %a{"data-toggle" => "tab", href: "#exercises", class: 'tab-button'} My Exercises
  %li
    %a{"data-toggle" => "tab", href: "#stats", class: 'tab-button'} My Stats
  %li
    %a{"data-toggle" => "tab", href: "#competitions", class: 'tab-button'} My Competitions
  %li
    %a{"data-toggle" => "tab", href: "#challanges", class: 'tab-button'} My Challenges
  %li
    %a{"data-toggle" => "tab", href: "#settings", class: 'tab-button'} Settings

app/views/users/_tabs.html.haml
.tab-content
  #exercises.tab-pane.active
    %h2 Exercises
    %hr
    %a.btn.btn-primary.btn-lg{"data-toggle" => "modal", href: "#exerciseModal"} Add Exercise
    = render partial: "exercises/form"
    %br
    %br
    .text-center
      = link_to "<", {date: @date.prev_week, tab: 'exercises'}
      = exercise_date_range(@date)
      = link_to ">", {date: @date.next_week, tab: 'exercises'}
    %ul{id: "user_exercises"}
      - @user.exercises_by_date(@date).each do |exercise|
        = render exercise
      %table.table.table-condensed.table-bordered
        %tr
          - exercise_date_days(@date).each do |day|
            %th
              = format_date(day)
        %tr
          - exercise_date_days(@date).each do |day|
            %td
              %ul
                -unless @user.exercises_by_date(day).empty?
                  - @user.exercises_by_date(day).each do |exercise|
                    %li
                      = exercise.name  
  #stats.tab-pane
    %h2 My Stats
    %hr
    %table.table.table-condensed.table-bordered

    = form_tag nil do
      = select_tag :chart, options_from_collection_for_select(ExerciseType.all, 'id', 'name')  
      = radio_button_tag :reps, value: "reps"
      = label_tag :reps
      = radio_button_tag :distance, value: "distance"
      = label_tag :distance
      = radio_button_tag :duration, value: "duration"
      = label_tag :duration
      = radio_button_tag :weight, value: "weight"
      = label_tag :weight
      = radio_button_tag :calories, value: "calories"
      = label_tag :calories
    #statChart{style: "min-width: 310px; height: 400px; margin: 0 auto"}  
  #competitions.tab-pane 
    %h2 My Competitions
    %hr
    %h4 Competition Wins
    %ul
      -if @user.competitions_won.empty?
        %li No competitions won yet
      -else
        - @user.competitions_won.each do |comp|
          %li
            = link_to comp.name, competition_path(comp)

    %h4 My Current Individual Competitions
    %ul
      -if @user.active_individual_competitions.empty?
        %li Not registered for any individual competitions
      -else
        - @user.active_individual_competitions.each do |comp|
          %li
            = render comp
    .clearfix
    %h4 My Current Team Competitions
    %ul
      -if @user.active_team_competitions.empty?
        %li Not registered for any team competitions
      -else
        - @user.active_team_competitions.each do |team_comp|
          %li
            = render team_comp
        
  #challanges.tab-pane
    %h2 My Challenges
    - if @user.challenges.any?    
      -@user.challenges.each do |challenge|
        %p
          = challenge.name
        %p
          -@user.challenge_attempts_by_challenge(challenge).each do |attempt|
            %p
              = attempt.formatted_completition_time
    - else
      %p.jumbotron
        You have not currently attempted any challenges. If you would like to attempt one now
        %a{href: "/challenges"}
          %button.btn.btn-default.btn-lg{type: "button"}
            %span.glyphicon.glyphicon-star
            Click Here
            %span.glyphicon.glyphicon-star
        or select "Challenges" from the navigation menu.
        
  #settings.tab-pane
    %h2 Settings
    = render 'users/edit'

app/views/users/edit.html.haml
%h2
  Editing #{@user.nickname}

= form_for @user do |f|
  .control-group
    = f.label "What your Mom calls you", class: "control-label"
    .controls
    = f.text_field :name, placeholder: "Name"

  .control-group
    = f.label "What your friends would call you, if they were smart", class: "control-label"
    .controls
    = f.text_field :nickname, placeholder: "Nickname"

  .control-group
    .controls
      = f.radio_button :gender, "Male", :checked => true 
      = label :gender, "Male"
      = f.radio_button :gender, "Female"
      = label :gender, "Female"
      = f.radio_button :gender, "Other"
      = label :gender, "Other"      

  .control-group
    = f.label "Your body's relative mass", class: "control-label"
    .controls
      = f.number_field :weight, placeholder: "Weight"
      %br
      %i (This will not be publicly shared, unless you want to!)

  .control-group
    = f.label :height, class: "control-label"
    .controls
      = f.number_field :height, placeholder: "Height"

  .actions
    = f.submit "Update", class: "btn btn-primary"
%p
  = link_to "Click here to change your email, password", edit_user_registration_path
%h3 Cancel my account
%p
  Unhappy? #{button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete}
= link_to "Back", :back

app/views/users/index.html.haml
%h1 Users
%ul
- @users.each do |user|
  %li
    = link_to user.name, user_path(user)
    = link_to user.nickname, user_path(user)

app/views/users/show.html.haml
.row
  .col-md-8
    = render 'users/menu'
    = render 'users/tabs'
    
  .col-md-2
    %h2 
      Profile for 
      = @user.index_name
    %ul
      %li 
        Email
        %br
        = @user.email
      %li{id: "user_level"} 
        Level
        %br
        = @user.level
      %li{id: "user_xp"} 
        Total Experience
        %br
        = @user.xp
      %li{id: "user_levelup"} 
        Experience for next level  
        %br
        = @user.xp_for_levelup

    -if @user.friends.any?
      %h2
        Friends
      %ul
        -@user.friends.each do |friend|
          %li
            = friend.name