config/routes.rb
Workoutwars::Application.routes.draw do
  root :to => "static#index"

  get '/user_exercises/users/:id', to: 'users#user_exercises'

  resources :challenge_attempts
  resources :exercise_types
  resources :competition_types
  resources :challenge_types
  
  resources :challenges do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end
  resources :exercises, only: [:new, :create, :destroy]
  resources :competitions do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end

  resources :competable_registrations, only: [:create, :destroy]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:index, :show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      devise_for :users
    end
  end 
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>  
<% end %>
  

app/views/shared/_footer.html.haml
%footer
  .container
    %p
      Senior Project By 
      %a{:href => "https://github.com/CerebralStorm", :rel => "external"}Cody Tanner
      |
      %a{:href => "https://github.com/madavik", :rel => "external"}Joey Gibson
      |
      %a{:href => "http://www.updateme.com", :rel => "external"}John Hanks
      |
      %a{:href => "https://github.com/charmainekeck", :rel => "external"}Charmaine Keck
      for the
      %a{:href => "http://www.utah.edu", :rel => "external"}University of Utah
      

app/views/shared/_header.html.haml
%h1
  Workout Wars

app/views/shared/_navbar.html.haml
%ul.nav.nav-pills.nav-stacked
  %li
    %div
      = link_to (image_tag "home.png", height: 80, width: 80), user_path(current_user)
    %div
      = link_to "My Profile", user_path(current_user)
  %li
    %div
      = link_to (image_tag "Internet.png", height: 80, width: 80), users_path, rel: 'users-link'
    %div
      = link_to "Users", users_path, rel: 'users-link'
  %li
    %div
      = link_to (image_tag "Globe.png", height: 80, width: 80), competitions_path, rel: 'competitions-link'
    %div
      = link_to "Competitions", competitions_path, rel: 'competitions-link'
  %li
    %div
      = link_to (image_tag "Man.png", height: 80, width: 80), challenges_path, rel: 'challenges-link'
    %div
      = link_to "Challenges", challenges_path, rel: 'challenges-link'    
  %li
    %div
      = link_to (image_tag "arrow left.png", height: 80, width: 80), destroy_user_session_path, method: :delete, rel: 'logout-link' 
    %div
      = link_to "Sign out", destroy_user_session_path, method: :delete, rel: 'logout-link'