config/routes.rb
Workoutwars::Application.routes.draw do
  root :to => "static#index"

  get '/user_exercises/users/:id', to: 'users#user_exercises'

  resources :challenge_attempts
  resources :exercise_types
  resources :competition_types
  resources :challenge_types
  
  resources :challenges do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end
  resources :exercises, only: [:new, :create, :destroy]
  resources :competitions do
    resources :competable_exercises, only: [:new, :create, :destroy]
    resources :teams
  end

  resources :competable_registrations, only: [:create, :destroy]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:index, :show, :update, :destroy]

  namespace :api do
    namespace :v1 do
      devise_for :users
    end
  end 
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :challenge_type
  belongs_to :difficulty

  # Polymorphic Associations
  has_many :competable_transactions, as: :transactable, dependent: :destroy
  has_many :competable_registrations, as: :registerable, dependent: :destroy
  has_many :competable_exercises, as: :competable, dependent: :destroy
  has_many :teams, as: :teamable, dependent: :destroy
  has_many :experience_sources, as: :experienceable

  # Associations
  has_many :challenge_attempts
  has_many :team_users, through: :competable_registrations, source: :user
  has_many :users, through: :challenge_attempts
  has_many :teams, as: :teamable, dependent: :destroy  

  accepts_nested_attributes_for :competable_exercises, allow_destroy: true

  validates_presence_of :name

  after_create :create_teams, :unless => Proc.new{ self.team == false }

  def completed_by?(user)
    challenge_attempts.exists?(user: user)
  end

  def challenge_attempts_by_user(user)
    challenge_attempts.where(user: user)
  end

  def create_teams
    count = self.number_of_teams - self.teams.count
    count.times do 
      self.teams.create!
    end
  end
end

app/models/challenge_type.rb
class ChallengeType < ActiveRecord::Base
  belongs_to :category

  def self.default_scope
    order('name ASC')
  end
end

app/controllers/challenges_controller.rb
 class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @attempt = ChallengeAttempt.new
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :reward, :difficulty_id, :challenge_type_id,
        :competable_exercises_attributes => [:id, :competable_id, :competable_type, :exercise_type_id, :limit, :_destroy])
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_challenge_exercise_fields.html.haml
%fieldset
  %table.table.table-condensed
    %tr
      %td
        = f.hidden_field :challenge_id, value: @challenge.id
        = f.label :exercise_type_id, class: "control-label"
      %td
        = f.collection_select(:exercise_type_id, ExerciseType.all, :id, :name, {}, {:class => 'exercise-select'})
      %td
        = f.label :limit, class: "control-label"
      %td
        = f.number_field :limit
      %td
        = f.hidden_field :_destroy
        = link_to "remove", '#', class: "btn btn-danger remove_fields"

app/views/challenges/_competable_exercise_fields.html.haml
%fieldset
  %table.table.table-condensed
    %tr
      %td
        = f.hidden_field :challenge_id, value: @challenge.id
        = f.label :exercise_type_id, class: "control-label"
      %td
        = f.collection_select(:exercise_type_id, ExerciseType.all, :id, :name, {}, {:class => 'exercise-select'})
      %td
        = f.label :limit, class: "control-label use_limit"
      %td
        = f.number_field :limit, class: "use_limit"
      %td
        = f.hidden_field :_destroy
        = link_to "remove", '#', class: "btn btn-danger remove_fields"

app/views/challenges/_form.html.haml
= form_for @challenge do |f|
  .row.challenge-form
    .col-md-4
      %h1 New Challenge
      %hr
      - if @challenge.errors.any?
        #error_explanation
          %h2= "#{pluralize(@challenge.errors.count, "error")} prohibited this challenge from being saved:"
          %ul
            - @challenge.errors.full_messages.each do |msg|
              %li= msg
      .control-group
        .controls
          = label :team, "Team"
          = f.radio_button :team, true
          = label :team, "Individual"
          = f.radio_button :team, false

      .control-group
        = f.label :name, "Challenge Name", class: "control-label"
        .controls
          = f.text_field :name

      .control-group.team_show
        = f.label :number_of_teams, "Number of Teams", class: "control-label"
        .controls
          = f.number_field :number_of_teams

      .control-group
        = f.label :challenge_type_id, "Victory Condition", class: "control-label"
        .controls
          = f.collection_select(:challenge_type_id, ChallengeType.all, :id, :name)

      .control-group
        = f.label :difficulty_id, "Difficulty Rating", class: "control-label"
        .controls
          = f.collection_select(:difficulty_id, Difficulty.all, :id, :level)

      .control-group
        = f.label :end_date, class: "control-label"
        .controls
          = f.text_field :end_date, class: "datepicker"

      .control-group
        = f.label :max_participants, class: "control-label"
        .controls
          = f.number_field :max_participants

      .control-group
        .controls
          = label :public, "Public"
          = f.radio_button :public, true
          = label :public, "Private"
          = f.radio_button :public, false
    
    .col-md-8  
      %h1 Exercises for this Challenge
      %hr
      -if @challenge.competable_exercises.empty?
        - @challenge.competable_exercises.build

      = link_to_add_fields "Add Another Exercise", f, :competable_exercises
      = f.fields_for :competable_exercises do |builder|
        = render 'competable_exercise_fields', f: builder
          
          
      .actions
        = f.submit 'Save Challenge', class: 'btn btn-lg btn-primary', rel: 'save-challenge-link'

app/views/challenges/edit.html.haml
%h1 Editing challenge

= render 'form'

= link_to 'Show', @challenge
\|
= link_to 'Back', challenges_path

app/views/challenges/index.html.haml
%h1 Listing challenges
= link_to 'New Challenge', new_challenge_path, class: "btn btn-lg btn-primary"
%hr
.row
  .col-md-10
    %table.table.table-condensed.table-bordered
      %tr
        %th Name
        %th Reward
        %th Difficulty
        %th Challenge type

      - @challenges.each do |challenge|
        %tr
          %td= link_to challenge.name, challenge
          %td= challenge.reward
          %td= challenge.difficulty_id
          %td= challenge.challenge_type.name
  .col-md-2

app/views/challenges/new.html.haml
%h1 New challenge

= render 'form'

app/views/challenges/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @challenge.name
%p
  %b Reward:
  = @challenge.reward
%p
  %b Difficulty:
  = @challenge.difficulty.level
%p
  %b Challenge type:
  = @challenge.challenge_type.name

= form_for @attempt do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :challenge_id, value: @challenge.id
  .actions
    = f.submit "Attempt this challenge", class: "btn btn-lg btn-primary"

- if @challenge.completed_by?(current_user) 
  %h3
    Completion Times
  %ul
    - @challenge.challenge_attempts.each do |attempt|
      %li
        = Time.at(attempt.completion_time).utc.strftime("%H:%M:%S")